// DCBS nieuwsartikelen — beheerd via https://www.dcbs.nl/nieuws/#beheer (niet met de hand bewerken).
// Bovenaan = nieuwste. cat = een van de diensten. link = LinkedIn-post. img = pad onder /assets/nieuws/.
window.DCBS_ARTICLES = [
  {"id": "news-2026-09-ap-ict-leverancier", "cat": "Privacy compliance", "date": "September 2026", "link": "https://www.linkedin.com/posts/the-data-compliance-builders_de-ap-klopt-aan-bij-uw-ict-leverancier-bent-activity-7508433991608385536-mimb", "title": "De AP klopt aan bij uw ICT-leverancier. Is uw bestuur voorbereid?", "summary": "In april kondigde de Autoriteit Persoonsgegevens (AP) aan dat zij preventief gaat controleren bij ICT-leveranciers die grote hoeveelheden persoonsgegevens verwerken namens hun klanten. Dat klinkt als een probleem van de leverancier. Maar wie goed kijkt, ziet dat de verantwoordelijkheid voor het grootste deel bij de opdrachtgever ligt, en onder de Cyberbeveiligingswet en DORA zelfs persoonlijk bij het bestuur. In dit artikel leggen we uit wat er verandert, hoe de drie regimes in elkaar grijpen, en hoe u leveranciersbeheer inricht dat een kritische blik van elke toezichthouder kan doorstaan.", "img": "/assets/nieuws/ap-ict-leverancier.webp"},
  {"id": "news-1", "cat": "AI compliance", "date": "Maart 2025", "link": "https://www.linkedin.com/posts/jeroendubach_ai-2027-a-realistic-scenario-of-ai-takeover-activity-7345686481031577600-liD5", "title": "AI2027: Superintelligente AI binnen twee jaar — zijn we er klaar voor?", "summary": "Het AI2027-scenario beschrijft een geloofwaardig pad naar transformatieve AI. Wat zijn de governance- en compliance-implicaties voor organisaties die vandaag al AI-systemen inzetten?"},
  {"id": "news-2", "cat": "Privacy compliance", "date": "2025", "link": "", "title": "Recordboete Vodafone Duitsland: €45 miljoen — lessen voor uw compliance-programma", "summary": "De grootste AVG-boete in Duitsland tot nu toe. Wat ging er mis bij Vodafone en welke concrete stappen kunt u zetten?"},
  {"id": "news-3", "cat": "AI compliance", "date": "2025", "link": "", "title": "AI & Grondrechten: een gestructureerde aanpak onder de EU AI Act", "summary": "De EU AI Act vereist Fundamental Rights Impact Assessments voor bepaalde hoog-risico AI-systemen. Een gestructureerde aanpak, stap voor stap."},
  {"id": "news-4", "cat": "Privacy compliance", "date": "2025", "link": "", "title": "Zeven jaar AVG-handhaving in Nederland: wat hebben we geleerd?", "summary": "Zeven jaar AVG-handhaving door de AP. Welke sectoren werden het hardst geraakt en wat betekent dit voor uw compliance-programma?"},
  {"id": "news-5", "cat": "AI compliance", "date": "2025", "link": "", "title": "Wanneer Claude brutaal wordt: AI-nieuwsgierigheid omzetten in governance-discipline", "summary": "Een onverwachte interactie met Claude onthult iets fundamenteels over AI-governance: onvoorspelbaar gedrag is geen incident, maar een ontwerpgegeven."},
  {"id": "news-6", "cat": "Privacy compliance", "date": "2025", "link": "", "title": "Tesla Robotaxi publieke pilot van start — maar wat met uw privacy?", "summary": "Autonome voertuigen verzamelen ongekende hoeveelheden data. Wat zegt de AVG over biometrische gegevens in de openbare ruimte?"},
  {"id": "news-7", "cat": "AI compliance", "date": "2024", "link": "", "title": "De risico’s van Generatieve AI: wat uw organisatie moet weten", "summary": "Generatieve AI prolifereert op de werkvloer. De juridische, privacy- en operationele risico’s op een rij."},
  {"id": "news-8", "cat": "AI compliance", "date": "2024", "link": "", "title": "AI-geletterdheid en verboden AI-praktijken onder de EU AI Act", "summary": "De EU AI Act introduceert een AI-geletterdheidsplicht én een lijst verboden praktijken. Wat beide betekenen voor uw organisatie."},
  {"id": "news-9", "cat": "Privacy compliance", "date": "2024", "link": "", "title": "Waarom het BC 5701 Privacy Keurmerk essentieel is voor gegevensverwerkers", "summary": "Het BC 5701 Privacy Keurmerk is uitgegroeid tot de marktstandaard voor betrouwbare gegevensverwerkers."}
];
