// DCBS nieuwsartikelen — nieuw artikel toevoegen kan ook via de knop "Artikel toevoegen" op de nieuwspagina.
// Voor de live site is dít bestand de bron: voeg bovenaan een item toe en publiceer.
// Velden: cat, date, title, summary, link (artikelpagina), img (optioneel: pad of data-URL voor de afbeelding).
window.DCBS_ARTICLES = [
  { id: 'news-1', cat: 'AI Compliance', date: 'Maart 2025', link: '/nieuws/ai2027-superintelligente-ai/', title: 'AI2027: Superintelligente AI binnen twee jaar — zijn we er klaar voor?', summary: 'Het AI2027-scenario beschrijft een geloofwaardig pad naar transformatieve AI. Wat zijn de governance- en compliance-implicaties voor organisaties die vandaag al AI-systemen inzetten?' },
  { id: 'news-2', cat: 'Privacy', date: '2025', link: '/nieuws/vodafone-boete-45-miljoen/', title: 'Recordboete Vodafone Duitsland: €45 miljoen — lessen voor uw compliance-programma', summary: 'De grootste AVG-boete in Duitsland tot nu toe. Wat ging er mis bij Vodafone en welke concrete stappen kunt u zetten?' },
  { id: 'news-3', cat: 'AI Compliance', date: '2025', link: '/nieuws/fria-fundamental-rights-impact-assessment/', title: 'AI & Grondrechten: een gestructureerde aanpak onder de EU AI Act', summary: 'De EU AI Act vereist Fundamental Rights Impact Assessments voor bepaalde hoog-risico AI-systemen. Een gestructureerde aanpak, stap voor stap.' },
  { id: 'news-4', cat: 'Privacy', date: '2025', link: '/nieuws/zeven-jaar-avg-handhaving-nederland/', title: 'Zeven jaar AVG-handhaving in Nederland: wat hebben we geleerd?', summary: 'Zeven jaar AVG-handhaving door de AP. Welke sectoren werden het hardst geraakt en wat betekent dit voor uw compliance-programma?' },
  { id: 'news-5', cat: 'AI Compliance', date: '2025', link: '/nieuws/claude-ai-governance-discipline/', title: 'Wanneer Claude brutaal wordt: AI-nieuwsgierigheid omzetten in governance-discipline', summary: 'Een onverwachte interactie met Claude onthult iets fundamenteels over AI-governance: onvoorspelbaar gedrag is geen incident, maar een ontwerpgegeven.' },
  { id: 'news-6', cat: 'Privacy', date: '2025', link: '/nieuws/tesla-robotaxi-privacy/', title: 'Tesla Robotaxi publieke pilot van start — maar wat met uw privacy?', summary: 'Autonome voertuigen verzamelen ongekende hoeveelheden data. Wat zegt de AVG over biometrische gegevens in de openbare ruimte?' },
  { id: 'news-7', cat: 'AI Compliance', date: '2024', link: '/nieuws/risicos-generatieve-ai/', title: 'De risico’s van Generatieve AI: wat uw organisatie moet weten', summary: 'Generatieve AI prolifereert op de werkvloer. De juridische, privacy- en operationele risico’s op een rij.' },
  { id: 'news-8', cat: 'AI Compliance', date: '2024', link: '/nieuws/ai-literacy-verplichting/', title: 'AI-geletterdheid en verboden AI-praktijken onder de EU AI Act', summary: 'De EU AI Act introduceert een AI-geletterdheidsplicht én een lijst verboden praktijken. Wat beide betekenen voor uw organisatie.' },
  { id: 'news-9', cat: 'Privacy', date: '2024', link: '/nieuws/bc-5701-privacy-keurmerk/', title: 'Waarom het BC 5701 Privacy Keurmerk essentieel is voor gegevensverwerkers', summary: 'Het BC 5701 Privacy Keurmerk is uitgegroeid tot de marktstandaard voor betrouwbare gegevensverwerkers.' }
];
